### ISSUE TITLE
Customer-Churn-Prediction

### ISSUE THREAD

**Issue by mohaneesh-03** [Anubhav-Goyal01/ML-Projects#111]
I want to add this project. I am using this dataset (https://www.kaggle.com/datasets/blastchar/telco-customer-churn). Please assign this project to me.

**Comment by Anubhav-Goyal01** [comment]
One such notebook is already in the repo @mohaneesh-03, can you add some other notebook??

**Comment by mohaneesh-03** [comment]
> One such notebook is already in the repo @mohaneesh-03, can you add some other notebook??

I can add a volume control project that uses hand gesture detection....but that's a opencv project..is it acceptable?

**Comment by Anubhav-Goyal01** [comment]
Yeah, please go ahead @mohaneesh-03

**Comment by mohaneesh-03** [comment]
Added the volume control project. Please accept the pr

**Comment by Anubhav-Goyal01** [comment]
Merged your PR
