### ISSUE TITLE
Train a Multiple Linear Regression model in the Sales prediction notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#12]
Currently, I have only trained a simple linear regression model in that notebook, use the other features as well and train a multiple linear regression model and find the R2_score.

**Comment by Vedant180** [comment]
Hii!! I would like to work on this.

**Comment by Divyansh3021** [comment]
Hii!! I would like to work on this, I have already done code.
