### ISSUE TITLE
add tree based regression models to sales prediction

### ISSUE THREAD

**Issue by aaryanshsahay** [Anubhav-Goyal01/ML-Projects#15]
add tree based models and compare results

**Comment by Surya-29** [comment]
Hi , can u assign this issue to me?

**Comment by aryanlath** [comment]
Can I work on this issue? I have prior experience on working with tree based models.

**Comment by Anubhav-Goyal01** [comment]
Yes you both can work on this one @Surya-29 you can add a decision tree model and @aryanlath you can add a random forest model

**Comment by SpyzzVVarun** [comment]
If we are adding DT and RF, the Big 3( catboost, xgb and lightgbm) should also be added to compare performance. Can you assign this to me?

**Comment by Anubhav-Goyal01** [comment]
Sure! Assigning it to you @SpyzzVVarun

**Comment by Anubhav-Goyal01** [comment]
It seems like 2 people are working on this same notebook which can lead to merge conflicts. @Divyansh3021  @shyanukant, you can reply to this comment to let me know who is working on it first, whoever replies first can make a commit first and second person can wait

**Comment by Divyansh3021** [comment]
> It seems like 2 people are working on this same notebook which can lead to merge conflicts. @Divyansh3021 @shyanukant, you can reply to this comment to let me know who is working on it first, whoever replies first can make a commit first and second person can wait


I can!!

**Comment by Anubhav-Goyal01** [comment]
Ok @Divyansh3021, go ahead

**Comment by SouravBiswal** [comment]
Can you assign me this? @Anubhav-Goyal01

**Comment by Anubhav-Goyal01** [comment]
Tree based models have already been added @SouravBiswal, maybe you can add support vector regressor model, I will assign it to you

**Comment by shreyasingh2003** [comment]
I think I can do this

**Comment by Anubhav-Goyal01** [comment]
I have already assigned this issue @shreyasingh2003, maybe you can go through some other notebooks in this repo and see if you can add something... Just send a PR if you find something

**Comment by SouravBiswal** [comment]
> Tree based models have already been added @SouravBiswal, maybe you can add support vector regressor model, I will assign it to you

Sure

**Comment by shyanukant** [comment]
> It seems like 2 people are working on this same notebook which can lead to merge conflicts. @Divyansh3021 @shyanukant, you can reply to this comment to let me know who is working on it first, whoever replies first can make a commit first and second person can wait

OK,
