### ISSUE TITLE
Plot loss curves of both ANN and CNN model in The Handwritten Digits classsification notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#29]
Create a function that plots the loss curves of both ANN and CNN models (accuracy vs val_accuracy and loss vs val_loss). Plot them in a single row (1 row, 2 columns)

**Comment by kmartin62** [comment]
Can you assign this to me?

**Comment by Anubhav-Goyal01** [comment]
Sure @kmartin62
