### ISSUE TITLE
Use 5 different ML models and try to predict chances of heart attack 

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#3]
In the heart attack prediction notebook, I have only used Deep learning to predict the chances of a heart attack. Your task is to add 5 different ML models to the notebook and check which one has the highest ROC AUC score. Also, plot a bar graph of those ROC AUC scores.

**Comment by aka-vm** [comment]
Hi.
I would like to work on this issue, can you assign it to me?

**Comment by Anubhav-Goyal01** [comment]
Sure @aka-vm
