### ISSUE TITLE
Create a function which plots 10 different digits

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#32]
Currently, in the handwritten digits notebook, only 1 digit has been visualized. Create a function that can plot 10 digits (2 rows, 5  columns)

**Comment by AaryanSingh0017** [comment]
Plz assign this to me

**Comment by Anubhav-Goyal01** [comment]
Done @AaryanSingh0017

**Comment by dhruvkej9** [comment]
plz assign this to me i can do this

**Comment by Anubhav-Goyal01** [comment]
Done @dhruvkej9
