### ISSUE TITLE
Add CNN in Fashion dataset notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#33]
Currently, only ANN has been used to predict the different type of cloths, try training a CNN and check whether it improves the accuracy. Visualize the prediction as well

**Comment by Anjali2201** [comment]
I have tried applying CNN to this fashion dataset. Would like to submit pr for review

**Comment by Anubhav-Goyal01** [comment]
Sure @Anjali2201, make a PR
