### ISSUE TITLE
Add ANN in students exam performance notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#40]
I have only used Random Forest as of now to predict the math score, add an ANN to that notebook

**Comment by anandha24** [comment]
Can I add regression model with RNN that use Bi-LSTM?

**Comment by Anubhav-Goyal01** [comment]
Yes, you can! Go ahead @anandha24

**Comment by anandha24** [comment]
i want to ask something, before you give the model to predict, the math score is dropped right? and not use in predicting the grade because the math score have least corellated to each other?

**Comment by Anubhav-Goyal01** [comment]
Yes @anandha24, math score is the one we are looking to predict

**Comment by anandha24** [comment]
okay, i get it
