### ISSUE TITLE
Common Reusable Snippets

### ISSUE THREAD

**Issue by aka-vm** [Anubhav-Goyal01/ML-Projects#41]
I would Like to create a notebook that contains common snippets, which can be reused with little modifications by others.

These are the snippets I propose- 
* Confusion matrix Heatmap
* Classification report heatmap
* barplot from dataframe of performance
* Image Visualization - tells class, also tells if the predicted class is right/wrong.

**Comment by aka-vm** [comment]
Can you assign this issue to me?

**Comment by Anubhav-Goyal01** [comment]
Sure @aka-vm, that would be a really helpful notebook.

**Comment by prakhar-198** [comment]
Is there something left to be done? kindly assign me!

**Comment by Anubhav-Goyal01** [comment]
Hi @prakhar-198, I don't think this kind of file has been added yet in this repo, you can go ahead and create one if you wish

**Comment by Varad0124** [comment]
Hi @Anubhav-Goyal01 I can work on this issue, you can assign this issue to me.

**Comment by Anubhav-Goyal01** [comment]
Assigned it to you @Varad0124

**Comment by Aman123lug** [comment]
assign meee @Anubhav-Goyal01

**Comment by Anubhav-Goyal01** [comment]
Assigned @Aman123lug

**Comment by Aman123lug** [comment]
@Anubhav-Goyal01 bro in which you want to update

**Comment by Anubhav-Goyal01** [comment]
Hello @Aman123lug, there is no such file present in the repo, you will have to write a new script

**Comment by YuvrajRakheja** [comment]
@Anubhav-Goyal01 I can create it pls assign it to me.I have prior experience in data science projects.I will complete it by day after tomorrow

**Comment by Anubhav-Goyal01** [comment]
Ok @YuvrajRakheja assigning it to you

**Comment by aka-vm** [comment]
@YuvrajRakheja @Anubhav-Goyal01 

I was working on this issue...
Will make the PR shortly.

@YuvrajRakheja , if you do it before, please mention it on a comment. I'll add the changes.

**Comment by YuvrajRakheja** [comment]
@Anubhav-Goyal01 I have made common reusable snippets  colab notebook

**Comment by YuvrajRakheja** [comment]
Github link-->https://github.com/YuvrajRakheja/HacktoberFest-Task/blob/main/Common_Reusable_Snippets.ipynb
