### ISSUE TITLE
Add 3 new plots in the California Housing Notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#5]
Go to the California housing notebook and find 3 different insights from the data. In other words, add 3 different plots in the notebook and draw some conclusions from them.

**Comment by Aman123lug** [comment]
@Anubhav-Goyal01  assign me this

**Comment by Anubhav-Goyal01** [comment]
Sure @Aman123lug

**Comment by Aman123lug** [comment]
@Anubhav-Goyal01  how can i download this? its editable

**Comment by Anubhav-Goyal01** [comment]
You will have to first fork it and then clone the project @Aman123lug, I would suggest learning about GitHub first if you are new to open source. You can start by watching [this](https://www.youtube.com/watch?v=apGV9Kg7ics) video

**Comment by Aman123lug** [comment]
@Anubhav-Goyal01  sorry i am new okay i will clone it

**Comment by Anubhav-Goyal01** [comment]
It's alright @Aman123lug, take your time

**Comment by Aman123lug** [comment]
@Anubhav-Goyal01  i start working from now man

**Comment by Aman123lug** [comment]
@Anubhav-Goyal01  done your work assign me another work
