### ISSUE TITLE
Distractors generation using sentence transformer

### ISSUE THREAD

**Issue by Vis03al** [Anubhav-Goyal01/ML-Projects#58]
Hey would like to contribute by making a distractor generation for a particular word with the help of a sentence transformer
Can I be assigned this project

**Comment by Anubhav-Goyal01** [comment]
Done @Vis03al

**Comment by Vis03al** [comment]
@Anubhav-Goyal01 Pull request done!

**Comment by Anubhav-Goyal01** [comment]
Merged it
