### ISSUE TITLE
Make a Confidence Interval in the House Rent Prediction Notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#6]
Currently, the Rent prediction is only a single number. Try to make a 95% Confidence Interval, you might need to use scipy library for this task

**Comment by ag-yash** [comment]
Hey, I would like to contribute to this issue. Can you please assign me?

**Comment by Anubhav-Goyal01** [comment]
Sure @ag-yash

**Comment by ag-yash** [comment]
Just to confirm, @Anubhav-Goyal01. You want Prediction Interval right?

**Comment by Anubhav-Goyal01** [comment]
Yes @ag-yash

**Comment by SouravBiswal** [comment]
Can you assign this to me? @Anubhav-Goyal01

**Comment by prakhar-198** [comment]
Is there anything left to be done? kindly assign me

**Comment by Anubhav-Goyal01** [comment]
Assigning it to you @SouravBiswal

**Comment by KhushiPorwal** [comment]
Hii, I would also like to contribute to this issue. Can you please assign it to me?

**Comment by Anubhav-Goyal01** [comment]
Sure @KhushiPorwal

**Comment by Aman123lug** [comment]
man i am not able to fork this @Anubhav-Goyal01
