### ISSUE TITLE
Want to contribute my selenium scraped indian car dataset from various car websites.

### ISSUE THREAD

**Issue by Tejaswi-Kumar** [Anubhav-Goyal01/ML-Projects#61]
This dataset includes various features and can be used for EDA as well as recommendation systems. Please assign this task so that i can contribute to the repo.

**Comment by Anubhav-Goyal01** [comment]
Sure! Add that dataset in the Data folder. I will assign it to you @Tejaswi-Kumar

**Comment by Tejaswi-Kumar** [comment]
Hey thanks for assigning the task, I have raised a pull request #62 . Please check and review it and if everything is in order close this issue.

Thanks and regards!

**Comment by Anubhav-Goyal01** [comment]
I merged your PR
