### ISSUE TITLE
Add a new feature in the Titanic Notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#8]
Age clearly played a key role in determining whether a person survived the titanic crash or not. Create an `age bucket` feature (for e.g. assigning 1 to the people aged between 0 and 20) using the existing Age feature and check whether it improves the accuracy or not.

**Comment by rahul-aggarwal000005** [comment]
Hii !! 
I want to work on this issue.

**Comment by Anubhav-Goyal01** [comment]
Assigned it to you @rahul-aggarwal000005
