### ISSUE TITLE
Make a Confidence Interval in the California House Price Prediction Notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#9]
Currently, the California House prediction is only a single number. Try to make a 95% Confidence Interval, you might need to use the scipy library for this task

**Comment by aryanlath** [comment]
Hi @Anubhav-Goyal01 ! Can you explain this issue a bit so that I can work on it?

**Comment by Anubhav-Goyal01** [comment]
You can check out [this](https://www.geeksforgeeks.org/how-to-plot-a-confidence-interval-in-python/) article @aryanlath

**Comment by Surya-29** [comment]
@Anubhav-Goyal01 I'll work on this issue.
Can u assign it to me ?

**Comment by Anubhav-Goyal01** [comment]
Sure @Surya-29
