### ISSUE TITLE
Wanted to contribute car purchase dataset as well as EDA upon that dataset

### ISSUE THREAD

**Issue by Tejaswi-Kumar** [Anubhav-Goyal01/ML-Projects#95]
I have scraped a car purchase dataset and have done an in-depth Exploratory Data Analysis on this dataset and wanted to contribute to this repo.

**Comment by Anubhav-Goyal01** [comment]
Sure @Tejaswi-Kumar, make a PR

**Comment by Tejaswi-Kumar** [comment]
Hey, I have raised a PR regarding the same issue, please accept if there are no issues.
Thanks and Regards!
